name: psutil-process-monitoring-snap 
version: '1.0.0'
summary: psutil-process-monitoring-snap 
description: |
  Process monitoring snap using cross-platform lib psutil
base: core18
confinement: devmode

apps:
  psutil-process-monitoring-snap:
     command: bin/psutil-process-monitoring-snap
parts:
  psutil-process-monitoring-snap:
    plugin: python
    python-version: python3
    source: .
    python-packages :
       - pandas==1.2.0
       - psutil==5.8.0

