name: psutil-process-monitoring-snap 
version: '1.0.0'
summary: psutil-process-monitoring-snap 
description: |
  Process monitoring snap using cross-platform lib psutil
base: core18
confinement: devmode

apps:
  psutil-process-monitoring-snap:
     command: sudo python3 psutil-process-monitoring-snap.py
     daemon: simple
     restart-condition: always
     
parts:
  psutil-process-monitoring-snap:
     plugin: python
     python-version: python3
     source: .
     python-packages: [psutil]
