name: psutil-process-monitoring-snap
version: '1.0.0'
summary: psutil-process-monitoring-snap
description: |
  Process monitoring snap using cross-platform lib psutil
base: core18
confinement: devmode

apps:
  psutil_process_monitoring_snap:
     command: bin/psutil-process-monitoring-snap
parts:
  psutil_process_monitoring_snap:
    plugin: python
    python-version: python3
    source: .
